In [5]:
import torch
import torch.nn as nn

relu = nn.ReLU()

input_data = torch.tensor([[ 0.0401, -0.9005,  0.0397, -0.0876]])

weight_1 = torch.tensor([[-0.1094, -0.8285,  0.0416, -1.1222],
        [ 0.3327, -0.0461,  1.4473, -0.8070],
        [ 0.0681, -0.7058, -1.8017,  0.5857],
        [ 0.8764,  0.9618, -0.4505,  0.2888]])

weight_2 = torch.tensor([[ 0.6856, -1.7650,  1.6375, -1.5759],
        [-0.1092, -0.1620,  0.1951, -0.1169],
        [-0.5120,  1.1997,  0.8483, -0.2476],
        [-0.3369,  0.5617, -0.6658,  0.2221]])

weight_3 = torch.tensor([[ 0.8824,  0.1268,  1.1951,  1.3061],
        [-0.8753, -0.3277, -0.1454, -0.0167],
        [ 0.3582,  0.3254, -1.8509, -1.4205],
        [ 0.3786,  0.5999, -0.5665, -0.3975]])

In [6]:

weight_composed = torch.mm(weight_1, weight_2)
weight = torch.mm(weight_composed, weight_3)

output_composed = torch.mm(input_data, weight)

# now linearly 

hidden_1 = torch.mm(input_data, weight_1)
hidden_2 = torch.mm(hidden_1, weight_2)
output = torch.mm(hidden_2, weight_3)

print(output_composed)
print(output)

tensor([[0.2653, 0.1311, 3.8219, 3.0032]])
tensor([[0.2653, 0.1311, 3.8219, 3.0032]])


In [7]:
# now with activation function

import torch.nn as nn

relu = nn.ReLU()

hidden_composed_activated = relu(torch.mm(weight_1,weight_2))
weight_composed_ = torch.mm(hidden_composed_activated, weight_3)
output_composed_ = torch.mm(input_data, weight_composed_)

# now linearly

hidden_1_activated = relu(torch.mm(input_data, weight_1))
hidden_2_activated = relu(torch.mm(hidden_1_activated, weight_2))
output_ = torch.mm(hidden_2_activated, weight_3)

print(output_composed_)
print(output_)

tensor([[-0.2117, -0.4782,  4.0438,  3.0417]])
tensor([[-0.2770, -0.0345, -0.1410, -0.0664]])


In [4]:
print(input_data)

tensor([[ 0.0401, -0.9005,  0.0397, -0.0876]])


In [31]:
relu(input_data)

tensor([[0.1862, 0.5202, 0.8959, 0.9144, 0.5468]])